# Refer to the Gradle documentation for more information on version catalogs:
# https://docs.gradle.org/current/userguide/version_catalogs.html

[versions]
agp = "8.7.3"
androidJUnit5 = "1.11.3.0"
androidMaterial = "1.12.0"
androidxActivity = "1.10.0"
androidxAnnotations = "1.9.1"
androidxAppCompat = "1.7.0"
androidxConstraintlayout = "2.2.0"
androidxLifecycle = "2.8.7"
androidxTestExtEspressoCore = "3.6.1"
androidxTestExtJUnit = "1.2.1"
hamcrest = "3.0"
junit4 = "4.13.2"
junit5 = "5.11.3"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotations" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidxLifecycle" }
androidx-test-ext-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestExtEspressoCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJUnit" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJUnit5" }

